---
language: python

python:
  - "2.7"

install:
  - python setup.py install
  - pip install -r test-requirements.txt
  - pip install coveralls

script:
  - python setup.py nosetests
  - python setup.py flake8

after_success:
  - coveralls
